### ISSUE TITLE
ParserSBGC32_ConvertCommunicationStatusToString (maybe some others) does not work correctly.

### ISSUE THREAD

**Issue by illusoryring** [basecamelectronics/sbgc32-serial-api#10]
Function ParserSBGC32_ConvertCommunicationStatusToString does not work correctly with uninitialized array. Garbage gets into the array instead of correct line termination, for example: COMMAND_RX_ERRORh�ٖ�
The problem is that the strlen() returns the length of the string not including the null character, and then memcpy copy string without that null character. A possible solution is to change the macro TEXT_LENGTH_ as follows:
#define		TEXT_LENGTH_(text)		text, (strlen(text) + 1)
Or just using strcpy().

**Comment by qsivey** [comment]
Yes, but it's okay cause TEXT_LENGTH_() macro gets a constant string in "" braces that has a "\0" character only at the end.
The <char *str> argument must accept a pointer to an already initialized (allocated in memory) array. Typically, this is a buffer with no strict size limitations. After some consideration, I decided not to add a null character to the end of the buffer in such functions. 
Anyway I will update the description of such functions to avoid confusion for other users.
