### ISSUE TITLE
Missing last value in quaternion array when calling SBGC32_ControlQuatStatus().

### ISSUE THREAD

**Issue by illusoryring** [basecamelectronics/sbgc32-serial-api#9]
The last 4-byte value is skipped in the function PostControlQuatStatus (the purpose of the variable bytesSkip is unclear).

**Comment by qsivey** [comment]
Hello!
There is no mistake here. The purpose of the bytesSkip variable is to skip the first 4 bytes - the DATA_SET 4u variable in a received command. This is an unnecessary part of the command that is already known in advance.
However, thanks to you, I discovered another error. If you're going to use this function change the next line https://github.com/basecamelectronics/sbgc32-serial-api/blob/f63f6f4afdc9bcd6a486f22af89692b0efb7cec3/serialAPI/modules/realtime/realtime.c#L1581
to gSBGC->_api->writeLong(gSBGC, flags);

Also, if it is important for you to receive the DATA_SET (sbgcControlQuatStatusFlag_t flags) back, replace the PostControlQuatStatus in the next string
https://github.com/basecamelectronics/sbgc32-serial-api/blob/f63f6f4afdc9bcd6a486f22af89692b0efb7cec3/serialAPI/modules/realtime/realtime.c#L1585
to NULL and include the ui32 dataSet variable at a beginning of the receive structure (ControlQuatStatusStruct from example)
